//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public Drug()
        {
            this.Stock = 0;
            this.MinimumInventoryLevel = 0;
            this.OptimalInventoryLevel = 0;
            this.Events = new HashSet<InventoryEvent>();
        }
    
        public int PZN { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Stock { get; set; }
        public int MinimumInventoryLevel { get; set; }
        public int OptimalInventoryLevel { get; set; }
    
        public virtual ICollection<InventoryEvent> Events { get; set; }
    }
}
