//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public Pharmacy.BusinessLayer.Data.FulfilmentState State { get; set; }
        public int DrugPZN { get; set; }
        public int PrescriptionId { get; set; }
    
        public virtual Drug PrescribedDrug { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
