//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.BusinessLayer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyContainer : DbContext
    {
        public PharmacyContainer()
            : base("name=PharmacyContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Drug> DrugSet { get; set; }
        public DbSet<InventoryEvent> InventoryEventSet { get; set; }
        public DbSet<Position> PositionSet { get; set; }
        public DbSet<ReplenishmentOrder> ReplenishmentOrderSet { get; set; }
    }
}
