//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int DrugPZN { get; set; }
        public int ReplenishmentOrderId { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual ReplenishmentOrder Order { get; set; }
    }
}
