//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.BusinessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public Prescription()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public Pharmacy.BusinessLayer.Data.PrescriptionState State { get; set; }
        public string IssuingPhysician { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> FulfilmentDate { get; set; }
        public int CustomerId { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
